#!/bin/bash
echo "🚀 Setup do projeto..."
echo ""
echo "1. Instale o PostgreSQL + pgvector"
echo "   bash scripts/install-postgres.sh"
echo ""
echo "2. Copie os arquivos grandes dos cards acima"
echo ""
echo "3. Configure o .env"
echo "   cd backend && cp .env.example .env"
echo ""
echo "4. Instale dependências"
echo "   cd backend && npm install"
echo "   cd frontend && npm install"
echo ""
echo "5. Crie o banco"
echo "   psql -U postgres -f database/schema.sql"
echo ""
echo "6. Inicie o backend"
echo "   cd backend && npm start"
